print('welcome to the tip calculaor.')
total_bill=int(input('what is the total bill?  '))
tip_percentage=int(input('what percentage tip would you like to give? 10,12 or 15?  '))
per=(tip_percentage)/100*(total_bill)
no_of_people=int(input('how many people to split the bill?  '))
final=(per)/(no_of_people)
print(f'each person should pay {final} ')
